name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Create settings file
        run: |
          echo '{
            "types": ["all", "default", "season", "season-animate", "green", "green-animate", "night-view", "night-green", "night-rainbow", "gitblock"],
            "years": [2024, 2023, 2022],
            "isOnlyContribution": false
          }' > settings.json
      
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_PATH: settings.json

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "更新 3D 贡献图 (Generated 3D Contribution Chart)"
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git push
